name: Feature request
description: Suggest an enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem would this feature address?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see happen?
      placeholder: High-level approach, alternatives considered
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
