name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - run: echo "noop node"
  build-python:
    runs-on: ubuntu-latest
    steps:
      - run: echo "noop python"
